# Node.js APIサーバー設定
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm install --production"]

[phases.build]
cmds = ["cd server && ls -la"]

[start]
cmd = "cd server && npm start"