[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install"

[build.nixpacksConfig]
providers = ["nodejs"]
nodeVersion = "20"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10