[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && node index.js"
healthcheckPath = "/api/test-cors"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10