[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
node_version = "20"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10